apiVersion: v1
kind: Service
metadata:
  name: ddg-search-service
spec:
  selector:
    app: ddg-search # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000