apiVersion: v1
kind: Service
metadata:
  name: ddg-search-service
spec:
  selector:
    app: ddg-search # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ddg-search
  namespace: default
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`api.bnei.dev`) && PathPrefix(`/ddg-search`)
      services:
        - kind: Service
          name: ddg-search-service
          namespace: ddg-search
          port: 80
      middlewares:
        - name: path-stripper
          namespace: ddg-search
  tls:
    secretName: api-certificate-secret

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: path-stripper
spec:
  stripPrefix:
    prefixes:
      - /ddg-search