basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.SearchResultResponse:
    properties:
      snippet:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This API provides search functionality using DuckDuckGo.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: DuckDuckGo Search API
  version: "1.0"
paths:
  /search:
    get:
      description: Search DuckDuckGo with optional limit
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      - description: Maximum number of results to return
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.SearchResultResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Search DuckDuckGo
      tags:
      - search
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
